### ISSUE TITLE
set up triggered builds of the maubot container when new versions of fedora are released

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/matrix-bots#10]
currently, we have fedora 38 hard coded in the dockerfile in the openshift setup.

we need to figure out how to get new image builds triggered when a new version of fedora is released.

@abompard said this was possible, just need to figure out how.

**Comment by abompard** [comment]
Done by https://pagure.io/fedora-infra/ansible/c/04f95e1969273ad683c9292f4abeb6e15542f2f3?branch=main
