### ISSUE TITLE
Better escaping for `^action` in a meeting

### ISSUE THREAD

**Issue by jwflory** [fedora-infra/matrix-bots#16]
The DEI Team held a meeting this week and trialed out Meetbot ([see HTML report here](https://meetbot-raw.stg.fedoraproject.org/dei-fedoraproject-org/2023-09-14/diversity.2023-09-14-12.56.html)). During the meeting, I wrote `^action` in the middle of a message and also escaped it in backticks, but the bot picked this up as an `^action` even though that was not the intention:

```
I don't think `^action` works yet, but I will try in case it does
```

Messages like that should not get recorded as actions in the minutes.

**Comment by ryanlerch** [comment]
there is still some movement on how to handle all the commands and stuff in maubot-meetings.

are you able to file this one over there (the exact same text will suffice) -- i just can't transfer it to https://github.com/GregSutcliffe/maubot-meetings/ because it is in a different org :)
