### ISSUE TITLE
Bug: inconsistent !help / !halp

### ISSUE THREAD

**Issue by michel-slm** [fedora-infra/matrix-bots#19]
Following up from https://github.com/GregSutcliffe/maubot-meetings/issues/41

Looks like !help now works in Fedora meetings but does not mark the message with the lifevest emoji to acknowledge, while !halp does nothing but mark the message.

Seems like the migration from !halp to !help was unfinished?

**Comment by ryanlerch** [comment]
This is working as expected -- !help is a zodbot command that gives you zodbot help.

!halp is a tag that is set up on our fedora meetbot instance to tag a message as needing help (tagging adds the emoji)

was there any other behaviour you were expecting?
